# trigger:
# - master
  
pr:
  branches:
    include:
      - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'acr1287'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'acr1287'
        command: 'push'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy Helm
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:

    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: '3.2.3'

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'TallerTech(1)(82089a1c-681b-401c-9565-e53f84ef4471)'
        azureResourceGroup: 'RG-DEVOPS-POC'
        kubernetesCluster: 'aks-test'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'charts/productsstore'
        releaseName: 'productsstore'
        arguments: '--set web.image.tag=$(tag) --set web.image.name=products-web --set namespace=helm-app'
